---
- name: Configure UUG VM
  hosts: all
  become: true
  roles:
    - { role: common, tags: always }
    - { role: basic-prog-pkgs, tags: ["cs101"] }
    - { role: adv-prog-pkgs, tags: ["cs261"] }
    - { role: robot-pkgs, tags: ["cs354"] }
    - { role: java-dev, tags: ["cs149"] }
    - { role: jgrasp, tags: ["cs149"] }
    - { role: drjava, tags: ["cs149"] }
    - { role: aptana, tags: ["cs101"] }
    - { role: finch, tags: ["cs101"] }
