---
# tasks file for robot-pkgs
- name: Add ROS repository
  apt_repository:
    repo: deb http://packages.ros.org/ros/ubuntu xenial main
    filename: 'ros-latest'
    state: present
- name: Add ROS key
  apt_key:
    keyserver: ha.pool.sks-keyservers.net
    id: 421C365BD9FF1F717815A3895523BAEEB01FA116
    state: present
- name: Update apt cache
  apt:
    update_cache: yes
- name: Install robot development packages
  apt: name={{ item }} state=present
  with_items:
    - ros-kinetic-desktop-full
- name: Add ROS kinetic bash entry
  lineinfile:
    name: "/etc/profile"
    regexp: 'kinetic'
    line: 'source /opt/ros/kinetic/setup.bash'
    insertafter: EOF
- name: Add ROS Turtlebot bash entry
  lineinfile:
    name: "/etc/profile"
    regexp: 'TURTLEBOT'
    line: 'export TURTLEBOT_3D_SENSOR=kinect'
    insertafter: EOF
- name: Init rosdep if missing
  command: rosdep init
  args:
    creates: /etc/ros/rosdep/sources.list.d/20-default.list
- name: Get users
  getent:
    database: passwd
- name: Update rosdep for each user
  command: rosdep update
  become: yes
  become_user: "{{ item.key }}"
  with_dict: "{{ getent_passwd }}"
  when: item.value.4 | match ("^/home/")
