---
# tasks file for wireless-printing
- name: Install printer packages
  apt: name={{ item }} state=present
  with_items:
    - cups-client
- name: Add printers
  shell: >
    lpadmin -p "{{ item.name }}" -E
    -v "{{ item.queue }}"
    -L "{{ item.descr }}"
    -m "drv:///sample.drv/generic.ppd"
    -o "Duplex=DuplexNoTumble"
    -o "Option1=True"
  with_items: "{{ printers }}"
