---
# tasks file for jgrasp
- name: Check JGrasp
  stat:
    path: '{{ jgrasp.zip }}'
  register: st
- block:
    - name: Fetch zip
      get_url:
        url: '{{ jgrasp.url }}'
        dest: '{{ jgrasp.zip }}'
        force: yes
    - name: Remove old directory
      file:
        path: '{{ jgrasp.install_path }}'
        state: absent
    - name: Unpack zip
      unarchive:
        dest: '{{ global_base_path }}'
        src: '{{ jgrasp.zip }}'
  when: st.stat.checksum|default("") != jgrasp.hash
- name: Install JGrasp desktop icon
  template:
    src: jgrasp.desktop.j2
    dest: /usr/local/share/applications/jgrasp.desktop
