---
# tasks file for Finch
- name: Check Finch
  stat:
    path: '{{ finch.zip }}'
  register: st
- block:
    - name: Create Finch directory
      file:
        path: '{{ finch.install_path }}'
        state: directory
    - name: Fetch Finch zip
      get_url:
        url: '{{ finch.url }}'
        dest: '{{ finch.zip }}'
        force: yes
    - name: Unpack Finch zip
      unarchive:
        dest: '{{ finch.install_path }}'
        src: '{{ finch.zip }}'
  when: st.stat.checksum|default("") != finch.hash
- name: Install Finch udev rule
  copy:
    src: 55-finch.rules
    dest: '/etc/udev/rules.d/'
- name: Install Finch udev rule
  copy:
    src: dance2.py
    dest: '{{ finch.install_path }}'
- name: Install Finch udev rule
  copy:
    src: maze.py
    dest: '{{ finch.install_path }}'
