---
# tasks file for common
- name: Create opt directory
  file:
    path: /opt/
    state: directory
- name: Create local applications directory
  file:
    path: /usr/local/share/applications/
    state: directory
- name: Refresh apt cache
  apt:
    update_cache: yes
- name: Find user bashrc
  find:
    paths: "/home/"
    patterns: ".bashrc"
    recurse: yes
    hidden: yes
    file_type: file
  register: all_user_bashrc
- name: Get users
  getent:
    database: passwd
- name: Copy stu-home desktop
  copy:
    src: stu-home.desktop
    dest: '{{ item.value.4 }}/Desktop'
    owner: '{{ item.value.1 }}'
    group: '{{ item.value.2 }}'
  with_dict: "{{ getent_passwd }}"
  when:
    - item.value.4 | match ("^/home/")
    - item.value.5 != "/bin/false"

