---
# tasks file for common
- name: Create opt directory
  file:
    path: /opt/
    state: directory
- name: Create local applications directory
  file:
    path: /usr/local/share/applications/
    state: directory
- name: Refresh apt cache
  apt:
    update_cache: yes
- name: Get users
  getent:
    database: passwd
- name: Build real user list
  set_fact:
    real_users: >-
      {{ real_users|default([]) +
      [ {'user': item.key, 'homedir': item.value.4,
      'uid': item.value.1, 'gid': item.value.2 } ] }}
  with_dict: "{{ getent_passwd }}"
  when:
    - item.value.4 | match ("^/home/")
    - item.value.5 != "/bin/false"
- name: Copy stu-home desktop
  copy:
    src: stu-home.desktop
    dest: '{{ item.homedir }}/Desktop'
    owner: '{{ item.uid }}'
    group: '{{ item.gid }}'
    mode: 0750
  with_items: "{{ real_users }}"
- name: Install Java runtime
  apt: name={{ item }} state=present
  with_items:
    - default-jdk
    - openjdk-8-jdk
    - openjdk-8-source
- name: Touch VM profile
  copy:
    src: csvmprofile
    dest: '{{ global_profile_path }}'
    mode: 0644
    owner: root
    group: root
    # prevent overwriting
    force: no
# dest becomes path in Ansible 2.3+
- name: Add profile to user bashrc
  lineinfile:
    dest: '{{ item.homedir }}/.bashrc'
    line: "source {{ global_profile_path }}"
    state: present
    insertafter: EOF
  with_items: "{{ real_users }}"
