---
# tasks file for common
- name: Create opt directory
  file:
    path: /opt/
    state: directory
- name: Create local applications directory
  file:
    path: /usr/local/share/applications/
    state: directory
- name: Refresh apt cache
  apt:
    update_cache: yes
- name: Get users
  getent:
    database: passwd
- name: Build real user list
  set_fact:
    real_users: >-
      {{ real_users|default([]) +
      [ {'user': item.key, 'homedir': item.value.4,
      'uid': item.value.1, 'gid': item.value.2 } ] }}
  with_dict: "{{ getent_passwd }}"
  when:
    - item.value.4 | match ("^/home/")
    - item.value.5 != "/bin/false"
- name: Copy stu-home desktop
  copy:
    src: stu-home.desktop
    dest: '{{ item.homedir }}/Desktop'
    owner: '{{ item.uid }}'
    group: '{{ item.gid }}'
  with_items: "{{ real_users }}"
