---
# tasks file for basic-prog-pkgs
- name: Install introductory development packages
  apt: name={{ item }} state=present
  with_items:
    - artha
    - bless
    - default-jdk
    - geany
    - idle
    - meld
    - openjdk-8-source
    - pinta
    - python-pygame
    - wireshark
    - fonts-crosextra-caladea
    - fonts-crosextra-carlito
    - libreoffice
    - libreoffice-templates
    - libreoffice-style-tango
    - logisim
- name: Get users
  getent:
    database: passwd
- name: Copy idlerc prefs
  copy:
    src: .idlerc
    dest: '{{ item.value.4 }}'
    owner: '{{ item.value.1 }}'
    group: '{{ item.value.2 }}'
  with_dict: "{{ getent_passwd }}"
  when:
    - item.value.4 | match ("^/home/")
    - item.value.5 != "/bin/false"

